CodeLab\Bundle\MailerBundle\Entity\MailingHistory:
    type: entity
    table: mailing_history
    repositoryClass: CodeLab\Bundle\MailerBundle\Entity\Repository\MailingHistoryRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        creationTime:  { type: datetime }
        sendAt:  { type: datetime }
        sentAt:  { type: datetime, nullable: true }
        hash:       { type: string}
        spoolType:     { type: string}
        priority:   { type: integer }
        state:        { type: string }
        sendAttempts:        { type: integer }
        errors:        { type: string, nullable: true }
        from:        { type: string, nullable: true }
        to:        { type: string }
        subject:        { type: string, nullable: true }
        body:        { type: string, nullable: true }
        charset:        { type: string, nullable: true }
        contentType:        { type: string, nullable: true }
        swiftMessageId:        { type: string, nullable: true }
        bcc:        { type: string, nullable: true }
        cc:        { type: string, nullable: true }
        replyTo:        { type: string, nullable: true }
        returnPath:        { type: string, nullable: true }
        readReceiptTo:        { type: string, nullable: true }
        boundary:        { type: string, nullable: true }

    lifecycleCallbacks: {}